title: 静岡県静岡市
description: 静岡市内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1AeS_hHAVPaoiATn8K6t3h63MaylDAaiO76RhTUbrXcY/export?format=csv&gid=0
repository: https://github.com/hota1024/iemeshi-shizuoka-city/
form_url: https://forms.gle/rp3Bed3AoyThS8so8
